name: Update Discord Widget

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
    - cron: "5,15,25,35,45,55 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Widget Updater
        run: node update.js
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

      - name: Wait before self-retry
        run: sleep 300

      - name: Self Trigger
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/update.yml/dispatches \
            -d '{"ref":"main"}'
